# Common settings of the global session (that apply to all Rails environments)
# are listed here. These may be overidden in the environment-specific section.
common:
  attributes:
    signed:
    - user
    - ident
    insecure:
    - account
    - seen
  integrated: true
  ephemeral: true

test:
  timeout: 60
  cookie:
    name: rs_gbl 
    domain: rightscale.local
  trust:
  - dev

development:
  timeout: 60
  cookie:
    name: rs_gbl
    domain: rightscale.local
  trust:
  - dev

staging:
  timeout: 60
  cookie:
    name: rs_gbl_moo
    domain: .rightscale.com
  trust:
  - moo
  - moo-us-west
  - moo1

production:
  timeout: 60
  cookie:
    name: rs_gbl
    domain: .rightscale.com
  trust:
  - my
  - meta

meta:
  timeout: 60
  cookie:
    name: rs_gbl
    domain: .rightscale.com
  trust:
  - meta
